

[package]
name = "rookandroll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
threadpool = "1.8.1"
lazy_static = "1.4.0"

[profile.dev]
debug = 2

[profile.release]
opt-level = 3
overflow-checks = false
lto = true
debug = true