[package]
name = "chess"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
rayon = "1.5.3"
log = "0.4.17"
simplelog = "^0.12.0"
chrono = "0.4.22"